
language: php

php:
  - 7.0
  - hhvm

sudo: false

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose

matrix:
  allow_failures:
    - php: hhvm
