sudo: required
dist: trusty
language: php

addons:
   chrome: stable

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.0
      env: setup=lowest
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

before_script:
   - php artisan passport:keys
   - touch database/database.sqlite
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve &

script:
   - vendor/bin/phpunit
   - php artisan dusk
