sudo: required
dist: trusty
language: php

addons:
   chrome: stable

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

before_script:
   - php artisan passport:keys
   - touch database/database.sqlite
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve 2>/dev/null &

script:
   - vendor/bin/phpunit
   - php artisan dusk
