
language: php

php:
  - 7.0

sudo: false

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

before_install:
  - npm install -g dredd@stable

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_success:
  - php artisan migrate:refresh --force --seed
  - dredd

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
