
language: php

php:
  - 7.0
  - hhvm

sudo: false

env:
  - DB_CONNECTION=sqlite
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

before_install:
  - npm install -g dredd@stable

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - touch database/database.sqlite
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit --verbose
  - dredd

matrix:
  allow_failures:
    - php: hhvm
