
language: php

php:
  - 7.0

sudo: false

services:
  - mysql

before_script:
  - travis_retry composer install --no-interaction
  - mysql -e 'CREATE DATABASE test;'

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
