
language: php

php:
  - 7.0

sudo: false

services:
  - mysql

before_install:
  - npm install -g dredd@stable

before_script:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_success:
  - mysql -e 'create database solder;'
  - php artisan migrate --force
  - php artisan passport:install
  - dredd

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
